### PR TITLE
Weekdays refactor

### PR DESCRIPTION
**Pull request by AleManni**
Hi! 
This fixes the previous PR :-)

### CODE REVIEW

**Comment by AleManni** [comment]
Hey Niclas,
Well thought, that happens by non writing tests (my bad 😅). I’d suggest however to get rid of the switch - it would be enough to set the app in French to break it and possibly crash.

Ideally, you want to store the day in coredata by its index in workdays class. Or any other non localized property. Not by its localized name.

So that if you set your app to French you won’t fetch your days in English and save them in French - possibly duplicating them if you don’t crash before.

If you need to quickly get from day name to its number, you can make a func or extension for that in weekdays shortNames.firstIndex(...)
Etc to make your code smoother.

Let me know how it goes!
Cheers
Alessandro

**Comment by Sockerjam** [comment]
If I understood you correctly I replaced the Switch statement and instead, I'm using the calendar property you created. This allows the long names to be saved in Core Data without unnecessary code.

I also set the calendar to take into account the location of the user so it gets saved in core data in their language. I tried it with French and it worked - the days were correctly sorted, etc. The other languages just gave me the English calendar, which I'm not sure of why yet.

I believe this does sort the problem of fetching the English names if you are French as you mentioned above. But will see if I can find out why the other languages gave me the English calendar.

**Comment by Sockerjam** [comment]
Hi Alessandro,

Fixed the issue of trying it in multiple languages. The app works now in different languages too :)

Feel free to have a look whenever you can

**Comment by Sockerjam** [comment]
Also, must say your code in the GroupAndSort function is brilliant. It took me a while to understand it but it's much more professional than what I did. I learned a lot from it. Thank you :)

**Comment by AleManni** [comment]
Fantastic, Will do Niclas! 😄

**Pull request merged**
